#cloud-config
autoinstall:
  version: 1

  identity:
    realname: "Leonardo"
    hostname: SatoruJyrai
    username: Leonardo
    password: "$y$j9T$adC3VfpIgWNMabaoZ.tKm1$QA5t.xktPbJpJ2JyTrU919KX5qvT.piQu9YdxpD7967"

  locale: pt_BR.UTF-8

  keyboard:
    layout: br
    variant: ""

  timezone: America/Sao_Paulo

  ssh:
    install-server: true
    allow-pw: true

  packages:
    - curl
    - wget
    - git
    - nano
    - vim
    - htop
    - unzip
    - zip
    - net-tools
    - software-properties-common
    - apt-transport-https
    - ca-certificates
    - gnupg
    - lsb-release

  storage:
    layout:
      name: lvm

  updates: security
  shutdown: reboot

  late-commands:
    - curtin in-target --target=/target -- bash -c 'mkdir -p /home/pantera/setup'
    - curtin in-target --target=/target -- bash -c 'wget -O /home/pantera/setup/dev_pro_ubuntu24_v2.sh https://raw.githubusercontent.com/TI-WATCH/Teste_Watch/main/dev_pro_ubuntu24_v2.sh'
    - curtin in-target --target=/target -- bash -c 'chmod +x /home/pantera/setup/dev_pro_ubuntu24_v2.sh'
    - curtin in-target --target=/target -- bash -c 'chown -R pantera:pantera /home/pantera/setup'
    - curtin in-target --target=/target -- bash -c 'bash /home/pantera/setup/dev_pro_ubuntu24_v2.sh > /home/pantera/setup/dev_pro_ubuntu24_v2.log 2>&1'
    - curtin in-target --target=/target -- bash -c 'chown pantera:pantera /home/pantera/setup/dev_pro_ubuntu24_v2.log'
